/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditIdRouteImport } from './routes/audit.$id'

const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIdRoute = AuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/audit/$id': typeof AuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit' | '/audit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit' | '/audit/$id'
  id: '__root__' | '/' | '/audit' | '/audit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$id': {
      id: '/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuditIdRouteImport
      parentRoute: typeof AuditRoute
    }
  }
}

interface AuditRouteChildren {
  AuditIdRoute: typeof AuditIdRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditIdRoute: AuditIdRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
